runtime: custom
env: flex
instance_class: F1

env_variables:
  DJANGO_SETTINGS_MODULE: config.settings
  GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/google_app_credentials.json

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.65
