runtime: custom
env: flex
instance_class: F4

env_variables:
  DJANGO_SETTINGS_MODULE: config.settings
  GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/google_app_credentials.json

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.7

resources:
  disk_size_gb: 30

readiness_check:
  path: "/health"
  check_interval_sec: 10
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 600  # Allow more time for model loading

