runtime: custom
env: flex
instance_class: F4

env_variables:
  DJANGO_SETTINGS_MODULE: config.settings
  GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/google_app_credentials.json
  # Cache transformers models locally
  TRANSFORMERS_CACHE: "/app/transformers_cache"
  HF_HOME: "/app/huggingface_cache"
  # Disable tokenizers parallelism to avoid threading issues
  TOKENIZERS_PARALLELISM: "false"
  # Optimize model loading
  TRANSFORMERS_OFFLINE: "0"
  HF_HUB_DISABLE_TELEMETRY: "1"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.8

resources:
  disk_size_gb: 20

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300  # Allow more time for model loading

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300  # Wait for model to load
