runtime: custom
env: flex
instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: config.settings
  GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/google_app_credentials.json

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.65

resources:
  disk_size_gb: 30

readiness_check:
  app_start_timeout_sec: 600
  timeout_sec: 60
  check_interval_sec: 10
  