runtime: custom
env: flex
instance_class: F1

env_variables:
  DJANGO_SETTINGS_MODULE: config.settings
  GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/google_app_credentials.json

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1

health_check:
  enable_health_check: true
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
